Repository bhilburn/powerlevel9k, pull requests merged in 2018-07, with the labels that each got.

#641 #632: Indicate `Rust` or `(rust)` for rust_version segment only if ic…
  functions/icons.zsh
  powerlevel9k.zsh-theme
  test/segments/rust_version.spec
Labels: bug, next

#783 Added a segment that shows the Java version.
  README.md
  functions/icons.zsh
  powerlevel9k.zsh-theme
Labels: new segment, next

#797 Fix wrapper slowness in vcs segment
  functions/vcs.zsh
Labels: enhancement, next, segment: vcs
